### ISSUE TITLE
Handle ENS error when there is no Web3 wallet available

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#54]
https://app.dework.xyz/nation3/app-2?taskId=52213f7d-c0f1-4b62-8545-6f4f9f794ea7

Unhandled promise rejections are making integration tests unstable:  https://github.com/nation3/app/runs/7461874997?check_suite_focus=true

> <img width="914" alt="Screen Shot 2022-07-22 at 11 56 24 AM" src="https://user-images.githubusercontent.com/95955389/180359285-fbcf33b1-30e5-4cd5-9f9f-fcb7d53a1741.png">

To reproduce, open https://app.nation3.org/ in a browser without Web3 support.

```
javascript
Uncaught (in promise) Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.6.1)
    at d.makeError (_app-f771c5453f43eeba.js:1:107374)
    at d.throwError (_app-f771c5453f43eeba.js:1:107494)
    at d.throwArgumentError (_app-f771c5453f43eeba.js:1:107549)
    at _app-f771c5453f43eeba.js:1:63972
    at Generator.next (<anonymous>)
    at s (_app-f771c5453f43eeba.js:1:63452)
```

**Comment by aahna-ashina** [comment]
@gregfromstl We're still getting the "Error: invalid address or ENS name" error:  https://github.com/nation3/app/issues/54

```javascript
_app-3a6d88a5b31a8566.js:1 Uncaught (in promise) Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.6.1)
    at d.makeError (_app-3a6d88a5b31a8566.js:1:107374)
    at d.throwError (_app-3a6d88a5b31a8566.js:1:107494)
    at d.throwArgumentError (_app-3a6d88a5b31a8566.js:1:107549)
    at _app-3a6d88a5b31a8566.js:1:63972
    at Generator.next (<anonymous>)
    at s (_app-3a6d88a5b31a8566.js:1:63452)
```


You can see it at https://app.nation3.org/liquidity for example, if you load the page in an incognito browser window.
