### ISSUE TITLE
NUMERIC_FAULT on /liquidity page

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#94]
Application error when typing more than 18 decimals as stake amount at https://app.nation3.org/liquidity

![liquidity_decimals](https://user-images.githubusercontent.com/95955389/185593507-04597b2a-b14f-4398-bf08-5e1ec29fd47a.gif)

```javascript
Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.6.1)
    at d.makeError (_app-6c618fae021f384d.js:1:107374)
    at d.throwError (_app-6c618fae021f384d.js:1:107494)
    at h (_app-6c618fae021f384d.js:1:49985)
    at m (_app-6c618fae021f384d.js:1:50990)
    at Module.u (_app-6c618fae021f384d.js:1:261202)
    at u (57-1a3a605a543a96c8.js:1:5929)
    at R (liquidity-5b716c9f1c561dc5.js:1:26463)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Wo (framework-5f4595e5518b5600.js:1:68979)
    at Ku (framework-5f4595e5518b5600.js:1:112703)
```

**Comment by jayito** [comment]
Check this codes.
https://github.com/jayito/nation_app/commit/a0e7b39fce3064b41149253016199115004b6968
